[workspace]
members = ["app", "server"]
resolver = "2"

[workspace.dependencies]
dioxus = { version = "0.6.0", features = ["router", "fullstack"] }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
